### ISSUE TITLE
No Devices Detected

### ISSUE THREAD

**Issue by ScottTeePee** [ashionky/refoss_ha#1]
Hi,

I have some Refoss MSS305 Smart Wi-Fi Plug Mini which work well in the Refoss app. However they are not detected when installing the Refoss integration. Could you help, please?

Thank you,

Scott

**Comment by ashionky** [comment]
Hello, Thank you for your feedback.  
Refoss in HA currently only supports r10. We will upgrade the firmware of MSS305 in the future ,  later update the HA support documents.
