### ISSUE TITLE
Refoss Smart Wi-Fi Garage Door Opener, RSG100HK Integration

### ISSUE THREAD

**Issue by TylerSchwerd** [ashionky/refoss_ha#2]
Is the Refoss Smart Wi-Fi Garage Door Opener, RSG100HK going to be supported (soon)?

**Comment by ashionky** [comment]
Hello, thank you for your feedback. We will develop supported firmware as soon as possible

**Comment by ashionky** [comment]
Hello,  We will consider your suggestion and thank you for your feedback。
