### ISSUE TITLE
Can’t add the EM06

### ISSUE THREAD

**Issue by Kesslermeinname** [ashionky/refoss_ha#3]
Hello, I saw that it’s now possible to add the EM06. I downloaded the zip file and read the instructions but I can’t find the components folder. I have installed file editor and samba share but the folder won’t show up.

does the main component allow adding the EM06 by UI soon?

**Comment by ashionky** [comment]
hi， The official support from HA has been approved and will be released by the end of the month。
now， Now you can integrate in this way：  https://github.com/Refoss/refoss-homeassistant
