### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by joostlek** [ashionky/refoss_ha#4]
Hey 👋🏻,

I am currently looking into licensing at Home Assistant, and I found that this library does not have a license. The library should get an OSI approved license in order to be allowed in core. Please update and bump in Home Assistant as soon as possible.

Thanks

**Comment by ashionky** [comment]
ok，thanks！

**Comment by joostlek** [comment]
Please also add the right classifiers to the `setup.py` file and do another release and bump in home assistant please :)

**Comment by joostlek** [comment]
Kind reminder to do a release and bump in Home Assistant :)

**Comment by ashionky** [comment]
Ok, I'll handle it as soon as possible，Thank you for the reminder

**Comment by ashionky** [comment]
@joostlek  Hello, A new PR has been submitted, Thanks
