### ISSUE TITLE
Adjust Update intervall

### ISSUE THREAD

**Issue by Schnullerbacke2** [ashionky/refoss_ha#6]
Hello,

I successfully installed the integration and all entities are available and get updated.
The initial refresh interval was around 15 seconds compared to a 5 seconds rate in the mobile app.
I intend to reduce the rate to 5 seconds in the integration as well.
Therefor I disabled “polling for updates” under system options of the integration and added an automation via the service “homeassistant.update_entity”.

No matter what refresh interval below 10 seconds I configure, the entities are always updated with an interval of around 10 seconds.
Some sort of default interval - seems to be the standard push interval, other than the 5 seconds of connection to the mobile app.

Is there a way to reduce the interval below 10 seconds?

**Comment by ashionky** [comment]
@Schnullerbacke2 
Thank you for your feedback, it is default.
In the next version, we will reduce this interval time。

**Comment by Schnullerbacke2** [comment]
OK, thank you for your prompt feedback.
Is there a rough timeline for the next release?

**Comment by ashionky** [comment]
Hello， Please submit a issuesto the HA official website（ https://github.com/home-assistant/core/issues），
my modifications may be approved earlier.
