### ISSUE TITLE
HA is in different subnet then refoss energy meter

### ISSUE THREAD

**Issue by mellaiz** [ashionky/refoss_ha#7]
How can i add manually ip address of refoss device?

HA and refoss are in different subnets and therefore integration doesnt see it.

**Comment by ashionky** [comment]
It must be on the same network.
Sorry, you have to reconfigure the wifi for your device

**Comment by mellaiz** [comment]
Do you store ip address in db or in yaml file somewhere? Can i manually specify ip address in code?

**Comment by ashionky** [comment]
The device was discovered and added through UDP broadcast, and the data is located in the config directory, including other device information。

**Comment by ashionky** [comment]
@mellaiz  Hello, please visit   https://github.com/Refoss/refoss-homeassistant  , See if it can solve your needs .
