### ISSUE TITLE
Any chance for more device support?

### ISSUE THREAD

**Issue by Liquidmasl** [ashionky/refoss_ha#8]
I just stupidly installed (in a way where its not easily removeable) a plug MSS620 without checking compatibility before.

Whats missing? can I help?

**Comment by ashionky** [comment]
Hello, currently MSS620 is no support available. We will consider your suggestion and thank you for your feedback。

**Comment by ashionky** [comment]
Hello, currently MSS620 is no support available. We will consider your suggestion and thank you for your feedback。

**Comment by Liquidmasl** [comment]
Tahnks for the response, I actually found another home assistant integration that supports it. 
**Meross Lan**, if anyone else is looking for it!
